# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.15.4'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [15]:
# Method 1 
a1 = np.random.random(size=(2,3,5))
a1

array([[[0.8516775 , 0.82556652, 0.67349631, 0.41391528, 0.35182677],
        [0.08408359, 0.71961118, 0.87340849, 0.24338718, 0.58964523],
        [0.09746144, 0.540653  , 0.97232098, 0.83830565, 0.79953406]],

       [[0.90143396, 0.85415624, 0.31336239, 0.47477648, 0.01728579],
        [0.9148919 , 0.25961067, 0.27944288, 0.67693735, 0.21464652],
        [0.21237762, 0.92316353, 0.09622925, 0.02641999, 0.02249612]]])

In [8]:
# Method 2
a2 = np.random.rand(2,3,5)
a2

array([[[0.91774382, 0.3005544 , 0.88713734, 0.89535726, 0.37675527],
        [0.26904893, 0.69568952, 0.87065027, 0.17029763, 0.93528298],
        [0.13928704, 0.34615446, 0.8026841 , 0.20059596, 0.59302085]],

       [[0.13574947, 0.06478402, 0.980332  , 0.37205102, 0.19125573],
        [0.69157633, 0.93149525, 0.54603165, 0.34229657, 0.35007208],
        [0.91854439, 0.91806999, 0.03759436, 0.00679812, 0.83481364]]])

In [13]:
# Method 3
a3 = np.random.randint (0,10, size=(2,3,5))
a3

array([[[8, 5, 2, 0, 3],
        [1, 8, 4, 7, 2],
        [7, 5, 9, 5, 7]],

       [[8, 5, 9, 5, 3],
        [5, 9, 7, 6, 5],
        [0, 5, 4, 4, 5]]])

#### 4. Print *a*.


In [16]:
# your code here
a1

array([[[0.8516775 , 0.82556652, 0.67349631, 0.41391528, 0.35182677],
        [0.08408359, 0.71961118, 0.87340849, 0.24338718, 0.58964523],
        [0.09746144, 0.540653  , 0.97232098, 0.83830565, 0.79953406]],

       [[0.90143396, 0.85415624, 0.31336239, 0.47477648, 0.01728579],
        [0.9148919 , 0.25961067, 0.27944288, 0.67693735, 0.21464652],
        [0.21237762, 0.92316353, 0.09622925, 0.02641999, 0.02249612]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [19]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [20]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [24]:
# your code here
a1.size
b.size
a1.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [25]:
# your answer here
a + b

#It's not possible because it's not able to sum matrices with different number of columns and lines

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [30]:
# your code here
np.reshape(b, (2,3,5))
a1.shape == b.shape
c = np.reshape(b, (2,3,5))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [38]:
# your code/answer here
c.shape == a1.shape
c + a1
d = c + a1
print(d)
# It worked because the number of lines of and columns of a1 and d are the same.

[[[1.8516775  1.82556652 1.67349631]
  [1.41391528 1.35182677 1.08408359]]

 [[1.71961118 1.87340849 1.24338718]
  [1.58964523 1.09746144 1.540653  ]]

 [[1.97232098 1.83830565 1.79953406]
  [1.90143396 1.85415624 1.31336239]]

 [[1.47477648 1.01728579 1.9148919 ]
  [1.25961067 1.27944288 1.67693735]]

 [[1.21464652 1.21237762 1.92316353]
  [1.09622925 1.02641999 1.02249612]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [40]:
# your code/answer here
print(a1)
print(d)
#the difference between values is +1 by each element

[[[0.8516775  0.82556652 0.67349631]
  [0.41391528 0.35182677 0.08408359]]

 [[0.71961118 0.87340849 0.24338718]
  [0.58964523 0.09746144 0.540653  ]]

 [[0.97232098 0.83830565 0.79953406]
  [0.90143396 0.85415624 0.31336239]]

 [[0.47477648 0.01728579 0.9148919 ]
  [0.25961067 0.27944288 0.67693735]]

 [[0.21464652 0.21237762 0.92316353]
  [0.09622925 0.02641999 0.02249612]]]
[[[1.8516775  1.82556652 1.67349631]
  [1.41391528 1.35182677 1.08408359]]

 [[1.71961118 1.87340849 1.24338718]
  [1.58964523 1.09746144 1.540653  ]]

 [[1.97232098 1.83830565 1.79953406]
  [1.90143396 1.85415624 1.31336239]]

 [[1.47477648 1.01728579 1.9148919 ]
  [1.25961067 1.27944288 1.67693735]]

 [[1.21464652 1.21237762 1.92316353]
  [1.09622925 1.02641999 1.02249612]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [43]:
# your code here
a1 * c
e = a1 * c
print(e)

[[[0.8516775  0.82556652 0.67349631]
  [0.41391528 0.35182677 0.08408359]]

 [[0.71961118 0.87340849 0.24338718]
  [0.58964523 0.09746144 0.540653  ]]

 [[0.97232098 0.83830565 0.79953406]
  [0.90143396 0.85415624 0.31336239]]

 [[0.47477648 0.01728579 0.9148919 ]
  [0.25961067 0.27944288 0.67693735]]

 [[0.21464652 0.21237762 0.92316353]
  [0.09622925 0.02641999 0.02249612]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [48]:
# your code/answer here
e == a1
# a1 has been multiplied by matrix c, which all elements are 1.

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [55]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9723209759242906
1.0172857865989142
1.5020707956222143


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [61]:
# your code here
f = np.empty([2,3,5])
f

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [0]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here